name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v1
        name: Setup Node Version
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run format:check
      - name: Run Tests with code coverage together
        run: npm test -- --coverage
        # We need to have CI=true to not cause interactive actions from npm
        env:
          CI: true
      - name: Build Project
        if: github.event_name == "push"
        run: npm run build
      # - name: Install Surge
      #   run: npm install --global surge
      # Instead we will install and run in one command
      - name: Deploy to Staging Surge
        if: github.event_name == "push"
        run: npx surge --project ./build --domain angry-babies.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

